// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ywmanjkwhrkeotgpyuns.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3bWFuamt3aHJrZW90Z3B5dW5zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3OTc1NDcsImV4cCI6MjA2MjM3MzU0N30.33J2BbDuAHz5k__5E3NRQIqXrnZqJR7yynMeCfUeQyA";

// Google OAuth credentials
const GOOGLE_CLIENT_ID = "913006690156-gnlndhmmqna9sbu7a9o8fknbovt4aqrs.apps.googleusercontent.com";
const GOOGLE_CLIENT_SECRET = "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";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage,
    flowType: 'pkce',
    // Configure auth providers
    detectSessionInUrl: true
  }
});
